"""auto-add phone number

Revision ID: 852938e6d163
Revises: 5c3b1192ad0f
Create Date: 2022-07-22 18:30:55.672659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852938e6d163'
down_revision = '5c3b1192ad0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
